require('dotenv').config();
const express=require('express'), jwt=require('jsonwebtoken'), bcrypt=require('bcryptjs'), {Pool}=require('pg');
const app=express(); const pool=new Pool({connectionString:process.env.DATABASE_URL}); const PORT=process.env.PORT||3000; const SECRET=process.env.JWT_SECRET||'dev-secret';
app.use(express.json()); app.use(express.static('public'));
function auth(req,res,next){const h=req.headers.authorization||''; if(!h.startsWith('Bearer ')) return res.status(401).json({error:'Authentication required'}); try{req.user=jwt.verify(h.slice(7),SECRET);next()}catch{return res.status(401).json({error:'Invalid token'})}}
function admin(req,res,next){if(req.user.role!=='admin')return res.status(403).json({error:'Admin only'});next()}
app.get('/api/health',async(_,res)=>{try{await pool.query('SELECT 1');res.json({ok:true})}catch(e){res.status(503).json({ok:false})}});
app.post('/api/register',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),pass=String(req.body.password||'');if(!email||pass.length<6)return res.status(400).json({error:'Email and password (6+ chars) required'});const hash=await bcrypt.hash(pass,10);const q=await pool.query('INSERT INTO users(email,password_hash) VALUES($1,$2) RETURNING id,email,role,demo_balance',[email,hash]);res.status(201).json(q.rows[0])}catch(e){res.status(400).json({error:e.code==='23505'?'Email already exists':'Registration failed'})}});
app.post('/api/login',async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase();const q=await pool.query('SELECT * FROM users WHERE email=$1',[email]);if(!q.rowCount||!(await bcrypt.compare(String(req.body.password||''),q.rows[0].password_hash)))return res.status(401).json({error:'Invalid credentials'});const u=q.rows[0];const token=jwt.sign({id:u.id,email:u.email,role:u.role},SECRET,{expiresIn:'7d'});res.json({token,user:{id:u.id,email:u.email,role:u.role,demo_balance:Number(u.demo_balance)}})});
app.get('/api/me',auth,async(req,res)=>{const q=await pool.query('SELECT id,email,role,demo_balance FROM users WHERE id=$1',[req.user.id]);res.json(q.rows[0])});
app.get('/api/matches',async(req,res)=>{const status=req.query.status;const args=[];let where='';if(['scheduled','live','finished'].includes(status)){args.push(status);where='WHERE m.status=$1'}const q=await pool.query(`SELECT m.*,COALESCE(json_agg(json_build_object('id',o.id,'market',o.market,'selection',o.selection,'price',o.price) ORDER BY o.id) FILTER(WHERE o.id IS NOT NULL),'[]') odds FROM matches m LEFT JOIN odds o ON o.match_id=m.id ${where} GROUP BY m.id ORDER BY m.starts_at`,args);res.json(q.rows)});
app.get('/api/bets',auth,async(req,res)=>{const q=await pool.query(`SELECT b.*,COALESCE(json_agg(json_build_object('match_id',l.match_id,'selection',l.selection,'price',l.price)),'[]') legs FROM demo_bets b LEFT JOIN demo_bet_legs l ON l.bet_id=b.id WHERE b.user_id=$1 GROUP BY b.id ORDER BY b.created_at DESC`,[req.user.id]);res.json(q.rows)});
app.post('/api/bets',auth,async(req,res)=>{const legs=Array.isArray(req.body.legs)?req.body.legs:[],stake=Number(req.body.stake);if(!legs.length||!Number.isFinite(stake)||stake<=0)return res.status(400).json({error:'Invalid bet'});const c=await pool.connect();try{await c.query('BEGIN');const u=(await c.query('SELECT demo_balance FROM users WHERE id=$1 FOR UPDATE',[req.user.id])).rows[0];if(Number(u.demo_balance)<stake)throw new Error('Insufficient demo balance');let total=1,checked=[];for(const l of legs){const q=await c.query(`SELECT m.id,m.status,o.price FROM matches m JOIN odds o ON o.match_id=m.id WHERE m.id=$1 AND o.selection=$2`,[l.match_id,l.selection]);if(!q.rowCount||q.rows[0].status==='finished')throw new Error('One selection is unavailable');total*=Number(q.rows[0].price);checked.push([l.match_id,l.selection,Number(q.rows[0].price)])}const ret=stake*total;const b=(await c.query('INSERT INTO demo_bets(user_id,stake,potential_return) VALUES($1,$2,$3) RETURNING id',[req.user.id,stake,ret])).rows[0];for(const x of checked)await c.query('INSERT INTO demo_bet_legs(bet_id,match_id,selection,price) VALUES($1,$2,$3,$4)',[b.id,...x]);await c.query('UPDATE users SET demo_balance=demo_balance-$1 WHERE id=$2',[stake,req.user.id]);await c.query('COMMIT');res.status(201).json({bet_id:b.id,potential_return:ret})}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message})}finally{c.release()}});
app.post('/api/admin/matches',auth,admin,async(req,res)=>{const {sport='Football',league='Demo League',home_team,away_team,starts_at}=req.body;if(!home_team||!away_team||!starts_at)return res.status(400).json({error:'Missing fields'});const q=await pool.query('INSERT INTO matches(sport,league,home_team,away_team,starts_at) VALUES($1,$2,$3,$4,$5) RETURNING *',[sport,league,home_team,away_team,starts_at]);res.status(201).json(q.rows[0])});
app.post('/api/admin/odds',auth,admin,async(req,res)=>{const {match_id,selection,price}=req.body;const q=await pool.query('INSERT INTO odds(match_id,selection,price) VALUES($1,$2,$3) ON CONFLICT(match_id,market,selection) DO UPDATE SET price=EXCLUDED.price RETURNING *',[match_id,selection,price]);res.json(q.rows[0])});
app.post('/api/admin/matches/:id/status',auth,admin,async(req,res)=>{const {status,home_score=0,away_score=0,minute=0}=req.body;if(!['scheduled','live','finished'].includes(status))return res.status(400).json({error:'Invalid status'});const c=await pool.connect();try{await c.query('BEGIN');const m=(await c.query('UPDATE matches SET status=$1,home_score=$2,away_score=$3,minute=$4 WHERE id=$5 RETURNING *',[status,home_score,away_score,minute,req.params.id])).rows[0];if(!m)throw new Error('Match not found');if(status==='finished'){const winner=Number(home_score)>Number(away_score)?'HOME':Number(home_score)<Number(away_score)?'AWAY':'DRAW';const bets=await c.query(`SELECT DISTINCT b.id,b.user_id,b.potential_return FROM demo_bets b JOIN demo_bet_legs l ON l.bet_id=b.id WHERE b.status='open' AND l.match_id=$1`,[m.id]);for(const b of bets.rows){const all=await c.query('SELECT l.selection,mm.status,mm.home_score,mm.away_score FROM demo_bet_legs l JOIN matches mm ON mm.id=l.match_id WHERE l.bet_id=$1',[b.id]);let won=true;for(const x of all.rows){if(x.status!=='finished'){won=false;break}const w=Number(x.home_score)>Number(x.away_score)?'HOME':Number(x.home_score)<Number(x.away_score)?'AWAY':'DRAW';if(x.selection!==w){won=false;break}}if(won){await c.query('UPDATE demo_bets SET status=\'won\' WHERE id=$1',[b.id]);await c.query('UPDATE users SET demo_balance=demo_balance+$1 WHERE id=$2',[b.potential_return,b.user_id])}else{await c.query('UPDATE demo_bets SET status=\'lost\' WHERE id=$1',[b.id])}}}await c.query('COMMIT');res.json(m)}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message})}finally{c.release()}});
app.get('*',(req,res)=>res.sendFile(require('path').resolve('public/index.html')));
app.listen(PORT,()=>console.log(`SportBet Demo running on http://localhost:${PORT}`));
